# Numpy Library
* Processing N-Dimensional Arrays

In [6]:
import numpy as np

li=[1,2,3,4,'a']

a=np.array(li)
#type(a)
a #---------------------->array(['1', '2', '3', '4', 'a'], dtype='<U11')
b=np.arange(15)
b #------------------>array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [8]:
#OneDimensional 
rn=np.random.randint(0,100,size=50)
rn

array([65, 98, 40, 19, 38, 49, 42, 92, 38, 26, 49, 97,  7, 81, 95, 76, 54,
       95, 80, 39, 25, 87, 98, 49, 79, 82, 85,  2, 37, 82,  4, 15, 23, 78,
       57, 69, 12, 29, 44, 69, 98, 65, 91, 48, 76, 49, 19, 10, 31, 70])

In [26]:
# 3 Dimensional Array
m3=np.random.randint(0,2,size=(3,3,3,3))
m3[2][2][2][1]

1

In [29]:
m3.ndim

4

In [30]:
m3.size

81

In [31]:
m3.shape

(3, 3, 3, 3)

In [32]:
m3.dtype

dtype('int32')

In [33]:
m3.itemsize

4

In [34]:
m3.nbytes

324

In [40]:
m3[2,-1]

array([[0, 1, 0],
       [0, 0, 1],
       [1, 1, 1]])

In [43]:
m3[1:2]

array([[[[0, 0, 0],
         [0, 0, 0],
         [1, 0, 1]],

        [[1, 0, 0],
         [0, 1, 1],
         [1, 1, 0]],

        [[0, 0, 0],
         [0, 0, 1],
         [1, 1, 0]]]])

In [47]:
x=np.random.randint(0,10,size=(3,4))
x

array([[5, 5, 7, 1],
       [9, 7, 8, 5],
       [0, 2, 2, 5]])

# PANDS
## UseCases
- DataAnalysis
- DataCleaning
-  DataTransformation
## Notations
* Series
* DataFrames

In [55]:
import pandas as pd

internal1={'s1':21,'s2':22,'s3':30}

internal1=pd.Series(internal1)

internal2={'s1':20,'s2':25,'s3':40}

internal2=pd.Series(internal2)

internal2

s1    20
s2    25
s3    40
dtype: int64

In [57]:
final={'internal1':internal1,'internal2':internal2}
final=pd.DataFrame(final)
final['internal1']

s1    21
s2    22
s3    30
Name: internal1, dtype: int64

In [58]:
final.columns

Index(['internal1', 'internal2'], dtype='object')

In [62]:
final.values # Lists of all rows

array([[21, 20],
       [22, 25],
       [30, 40]], dtype=int64)

In [63]:
final.values[2]

array([30, 40], dtype=int64)

In [65]:
final.values[2][0] # or[2,0]

30

In [70]:
for row in final.values:
    print('internal1-',row[0], 'internal2-',row[1])

internal1- 21 internal2- 20
internal1- 22 internal2- 25
internal1- 30 internal2- 40


In [74]:
final.loc['s4']=[15,20] # loc-->location
final

internal1  internal2
s1         21         20
s2         22         25
s3         30         40
3          15         20
s4         15         20

In [72]:
final.drop(3) # remove index

internal1  internal2
s1         21         20
s2         22         25
s3         30         40

In [75]:
final

internal1  internal2
s1         21         20
s2         22         25
s3         30         40
3          15         20
s4         15         20

In [76]:
final=final.drop(3)

In [77]:
final

internal1  internal2
s1         21         20
s2         22         25
s3         30         40
s4         15         20

In [78]:
final.values[2]=[12,25]

In [79]:
final

internal1  internal2
s1         21         20
s2         22         25
s3         12         25
s4         15         20

In [1]:
# Reading csv filedata
import pandas as pd
filepath='DataFiles/income.csv'
incomedf=pd.read_csv(filepath)
incomedf

GEOID       State   2005   2006   2007   2008   2009   2010   2011  \
0  04000US01     Alabama  37150  37952  42212  44476  39980  40933  42590   
1  04000US02      Alaska  55891  56418  62993  63989  61604  57848  57431   
2  04000US04     Arizona  45245  46657  47215  46914  45739  46896  48621   
3  04000US05    Arkansas  36658  37057  40795  39586  36538  38587  41302   
4  04000US06  California  51755  55319  55734  57014  56134  54283  53367   

    2012   2013  
0  43464  41381  
1  63648  61137  
2  47044  50602  
3  39018  39919  
4  57020  57528

In [6]:
# Average income of Arizona
sum=0
for i in range(2,11):
    sum+=incomedf.values[2][i]
sum/len(incomedf.values[2][2:])


47214.77777777778

In [7]:
# Average income of all states in year 2012
sum=0
for row in incomedf.values:
    sum+=row[-2]
sum/len(incomedf.values)

50038.8